### ISSUE TITLE
みんなに気づかれないように（コメントが流れないうちに）昔のタスクを亡き者にしたいです

### ISSUE THREAD

**Issue by ghost** [touhouota/scheduler#53]

**Comment by touhouota** [comment]
削除機能は実装予定。
しばし待たれよ・・・

**Comment by touhouota** [comment]
タスク削除について、とりあえずメモ(実装する方針)
・サブタスク：特に何も意識せずサヨナラできる
・親タスク：サブタスクをなきものとするのかどうかによる
　・親のみ削除、サブタスクは親タスクに格上げ
　・サブタスクもろとも削除
　　・=> 親タスクも実行・完了出来ると前者が良さそう

**Comment by touhouota** [comment]
削除機能を実装しましたー。
タスク右上にある点々にマウスオーバーすると、「削除」というボタンが出るはずです。
なお、削除する時はサブタスクもろとも消えるのでご注意を。
