### ISSUE TITLE
実行中のタスクなのかどうなのか判別つかなくなりました．

### ISSUE THREAD

**Issue by ghost** [touhouota/scheduler#65]

**Comment by touhouota** [comment]
タスク：ただの箱
サブタスク：これまでのタスク
という立ち位置。

**Comment by touhouota** [comment]
タスクも実行、停止できて
必要に応じてサブタスクを追加、とか出来るのが理想なんだけど、
現状ではサブタスク前提で作っています。

**Comment by touhouota** [comment]
タスクの状態によって、表示の色とか変えて状態をわかりやすくしよう。

**Comment by touhouota** [comment]
タスクの状態によって色分けしてみましたよ。
色が気持ち悪い、もっとこんな色がいい(濃く、薄く、別の色で)などあればどうぞ。

![2017-12-13 22 52 38](https://user-images.githubusercontent.com/13186385/33942153-59c9d774-e058-11e7-90f2-d720afcb7370.png)

**Comment by touhouota** [comment]
あ、ついでにタスク単体での実行でも出来るようになっています。
サブタスクがなくても、タスク単体で作業に取り組めます。

簡単なタスクであればそのまま。
考えてみれば幾つかのステップに別れるな、と思ったらサブタスクを入れて
入れ子にしてみてね。


↓スクショのタスクにはサブタスクが入ってないことに注目
![2017-12-13 22 55 26](https://user-images.githubusercontent.com/13186385/33942273-bea2a630-e058-11e7-9716-84620febe4fa.png)
