### ISSUE TITLE
通知が止まらない

### ISSUE THREAD

**Issue by ch4nk0** [touhouota/scheduler#87]
通知が多すぎてChromeが落ちてしまった
通知の上限数があると解消するかもしれません。

（先輩のツール以外の通知が混ざっているかもしれないですが・・・・）

**Comment by touhouota** [comment]
Chromeを落とせるツールを作ったぞ(絶句)
こちらでも状況を確認しつつ、対策を考えますね。

**Comment by touhouota** [comment]
通知が多くなるとブラウザの動作が極端に重くなることがわかった。
ということで、多くなったときになんとかする方法を考えなければいけない。

・複数ある時はまとめる？
どうやるのかは知らん。

**Comment by touhouota** [comment]
原因は通知ではなく、コメントの要素を追加する処理でした。
なぜかinsertBeforeを使っていたことが原因。
大量のコメントが追加された場合に処理が重くなっているようでした。

個々の処理を書き換えたので、ローカル環境では200件程度であれば十分問題なく動作するレベルで動くようになりました。
