### ISSUE TITLE
完了したタスクが今日の進捗の数に反映されてない

### ISSUE THREAD

**Issue by ch4nk0** [touhouota/scheduler#90]
トップ画面右上の今日の進捗の部分が完了したタスクがあるのに更新しても☑️ ×0のままでした

仲間の様子のDoneにはしっかり追加されてました
ちっちゃなバグかと思われます

**Comment by touhouota** [comment]
本日、問題なく動いてたときいた。
念のためローカルでテストしてみたが、問題なく動いているようなので閉じておく。
